"""Travel Conveyance claim-head schema (TRD section 8)."""
from __future__ import annotations

from app.rules.common import ClaimHeadSchema, FieldSpec

TRAVEL_SCHEMA = ClaimHeadSchema(
    key="TRAVEL_CONVEYANCE",
    label="Travel Conveyance",
    fields=(
        FieldSpec(
            name="from_location",
            label="From Location",
            value_type="text",
            anchors=(
                "from",
                "pickup",
                "pick up",
                "pick-up",
                "starting point",
                "start",
                "origin",
                "source",
                "boarding",
                "departure",
            ),
            negative_anchors=("from date", "valid from"),
            order=1,
        ),
        FieldSpec(
            name="to_location",
            label="To Location",
            value_type="text",
            anchors=(
                "to",
                "drop",
                "drop off",
                "drop-off",
                "dropoff",
                "destination",
                "arrival",
                "alighting",
            ),
            negative_anchors=("to date", "valid to", "total"),
            order=2,
        ),
        FieldSpec(
            name="bill_date",
            label="Bill Date",
            value_type="date",
            anchors=(
                "bill date",
                "invoice date",
                "receipt date",
                "transaction date",
                "trip date",
                "date of travel",
                "dated",
                "date",
            ),
            negative_anchors=("due date", "date of birth", "expiry date"),
            order=3,
        ),
        FieldSpec(
            name="bill_no",
            label="Bill No.",
            value_type="text",
            anchors=(
                "bill no",
                "bill number",
                "invoice no",
                "invoice number",
                "receipt no",
                "receipt number",
                "order no",
                "order number",
                "order id",
                "trip id",
                "reference no",
                "ref no",
                "bill #",
                "invoice #",
                # Till receipts label the number with the bare word and a
                # colon ("BILL:D785I/2526/3192"). Last, so the specific
                # two-word anchors above always outrank it.
                "bill",
                "invoice",
                "receipt",
            ),
            negative_anchors=(
                "bill date",
                "bill amount",
                "bill total",
                "bill to",
                "invoice date",
                "invoice amount",
                "invoice to",
                "receipt date",
            ),
            required=False,  # "Yes, if present" - stays null when absent (FR-08)
            order=4,
        ),
        FieldSpec(
            name="bill_amount",
            label="Bill Amount",
            value_type="money",
            anchors=(
                "grand total",
                "total amount payable",
                "amount payable",
                "total payable",
                "net amount",
                "net payable",
                "total fare",
                "total",
                "amount",
                "fare",
            ),
            negative_anchors=("subtotal", "sub total", "tax", "gst", "discount"),
            order=5,
        ),
        FieldSpec(
            name="currency",
            label="Currency",
            value_type="currency",
            anchors=("currency", "total", "grand total", "amount", "fare"),
            order=6,
        ),
        FieldSpec(
            name="remarks",
            label="Remarks",
            value_type="text",
            system_value="Travel Conveyance",
            order=7,
        ),
    ),
)
